### ISSUE TITLE
How can Nyx get branch coverage by "GCov" profiler?

### ISSUE THREAD

**Issue by cheolw00myung** [RUB-SysSec/Nyx#1]
Hi guys,

Nyx is super cool project. Applying nested virtualized fuzzing with Intel-PT is promising work. By the way, we are planning to check how much Nyx covers each branch coverage of virtual devices. However, we have trouble with collecting branch coverage using the "GCov" profiler. Could you share how Nyx modifies to get branch coverage?

Thank you in advance!

**Comment by schumilo** [comment]
GCov is not directly supported by Nyx. But there is a simple workaround: You can turn any `*.bin` from the corpus folder into a Hyper-Cube ISO image and then simply boot that specific image in QEMU or bhyve to measure code coverage via GCOV:
```
cd nyx_fuzzer/hypervisor_spec/build/hypertrash_os/
cp /tmp/workdir_qemu/corpus/normal/cnt_181.bin misc/crash.hexa
make clean hypertrash_os_crash.bin # this command will generate iso/hypertrash_os_bios_crash.iso
```

This works only if the *.bin file and OS use the same specification (basically all `*.h` files located in `nyx_fuzzer/hypervisor_spec/build/` such as `bytecode_spec.h` and `interpreter.h`). 

Btw: You will probably need to add specific signal handlers to QEMU to manually call `__gcov_flush()` due to GCOV and its limitations. Otherwise you will lose coverage data if QEMU crashes. 

Good luck with GCov :)
